version: '1.3'
summary:
    generatePRSummary: true
    customInstructions: ''
    behaviourForExistingDescription: 'concatenate'
    behaviourForNewCommits: 'none'
ignorePaths:
    - 'yarn.lock'
    - 'package-lock.json'
    - 'package.json'
    - '.env'
baseBranches: []
reviewOptions:
    security: true
    code_style: true
    kody_rules: true
    refactoring: true
    error_handling: true
    maintainability: true
    potential_issues: true
    documentation_and_comments: true
    performance_and_optimization: true
    breaking_changes: true
    bug: true
    performance: true
    cross_file: true
suggestionControl:
    groupingMode: 'full'
    limitationType: 'pr'
    maxSuggestions: 9
    severityLevelFilter: 'medium'
    applyFiltersToKodyRules: true
    severityLimits:
        low: 0
        medium: 0
        high: 0
        critical: 0
ignoredTitleKeywords: []
automatedReviewActive: true
pullRequestApprovalActive: false
isRequestChangesActive: false
runOnDraft: true
