services:
    kodus-orchestrator:
        image: ${IMAGE_NAME_PROD}
        container_name: ${CONTAINER_NAME}
        volumes:
            - log_volume:/app/logs
            - ./certs:/usr/src/app/certs:ro
        logging:
            driver: json-file
            options:
                max-size: '200m'
                max-file: '10'
        ports:
            - '3001:3001'
        environment:
            - ENV=production
            - API_NODE_ENV=production
            - NODE_OPTIONS=--max-old-space-size=4096 --max-semi-space-size=64
            - API_LOG_LEVEL=warn
            - API_LOG_PRETTY=false
        env_file:
            - .env.prod
        networks:
            - shared-network
        restart: unless-stopped

volumes:
    log_volume:

networks:
    shared-network:
        external: true
