ARG API_CLOUD_MODE=false

FROM node:22.14.0-slim AS deps

ARG API_CLOUD_MODE
ENV API_CLOUD_MODE=${API_CLOUD_MODE}

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y ca-certificates git make g++ python3 && rm -rf /var/lib/apt/lists/*

ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY package.json yarn.lock ./
COPY packages/kodus-flow ./packages/kodus-flow
COPY packages/kodus-common/package.json ./packages/kodus-common/

RUN yarn install --check-files --frozen-lockfile --production=false

# -------------------------------------------------------------
FROM deps AS build-code

ARG API_CLOUD_MODE
ENV API_CLOUD_MODE=${API_CLOUD_MODE}

COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY packages/kodus-flow ./packages/kodus-flow
COPY packages/kodus-common ./packages/kodus-common
COPY src ./src

ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN yarn build

RUN apt-get update && apt-get install -y git build-essential postgresql-client postgresql-server-dev-all && \
    cd /tmp && \
    git clone --branch v0.5.1 --depth 1 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install && \
    cd / && \
    rm -rf /tmp/pgvector && \
    apt-get remove -y git build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------
FROM node:22.14.0-slim AS development

ARG API_CLOUD_MODE
ENV API_CLOUD_MODE=${API_CLOUD_MODE}

WORKDIR /usr/src/app
EXPOSE 3001

RUN apt-get update && \
    apt-get install -y ca-certificates git python3 make g++ && \
    rm -rf /var/lib/apt/lists/*

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY --from=deps /usr/src/app/packages ./packages

COPY package.json yarn.lock ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

COPY --from=build-code /usr/src/app/dist ./dist
RUN mkdir -p /usr/src/app/certs

CMD ["yarn", "start:dev"]
